"""
Prompt Loader - Loads human forecasting prompts from simulation outputs

Reads the intelligence briefing prompts generated by the R simulation
and extracts the forecast question for LLM agents.
"""

from pathlib import Path
from typing import List, Dict, Optional
import re


def load_period_prompt(period: int, prompts_dir: str = None) -> str:
    """
    Load the forecasting prompt for a specific period

    Args:
        period: Period number (1-10)
        prompts_dir: Directory containing prompt files (default from config)

    Returns:
        Full prompt text for the period

    Raises:
        FileNotFoundError: If prompt file doesn't exist
        ValueError: If period is invalid
    """
    if period < 1 or period > 10:
        raise ValueError(f"Period must be between 1 and 10, got {period}")

    if prompts_dir is None:
        from forecasting.config import PROMPTS_DIR
        prompts_dir = PROMPTS_DIR

    prompt_file = Path(prompts_dir) / f"period_{period:02d}.txt"

    if not prompt_file.exists():
        raise FileNotFoundError(f"Prompt file not found: {prompt_file}")

    with open(prompt_file, 'r', encoding='utf-8') as f:
        prompt_text = f.read()

    return prompt_text


def extract_forecast_question(prompt_text: str) -> Dict[str, str]:
    """
    Extract the forecast question details from prompt text

    Args:
        prompt_text: Full prompt text

    Returns:
        Dictionary with keys:
        - question: The forecast question
        - deadline: Day number (e.g., "Day 35")
        - full_prompt: Original full prompt
    """

    # Extract forecast question section
    question_match = re.search(
        r'<forecast_question>(.*?)</forecast_question>',
        prompt_text,
        re.DOTALL
    )

    if not question_match:
        # Fallback: look for the question pattern directly
        question_match = re.search(
            r'what is the probability.*?by Day (\d+)',
            prompt_text,
            re.IGNORECASE | re.DOTALL
        )

    # Extract day number
    day_match = re.search(r'by Day (\d+)', prompt_text)
    deadline = f"Day {day_match.group(1)}" if day_match else "Unknown"

    # Extract the question text
    if question_match:
        question_text = question_match.group(1).strip() if question_match.lastindex else question_match.group(0).strip()
        # Clean up the question
        question_text = re.sub(r'Your probability estimate:.*', '', question_text, flags=re.DOTALL).strip()
        question_text = question_text.split('\n')[0]  # Get first line of question
    else:
        question_text = "What is the probability that Tethys's government will collapse or be removed from power?"

    return {
        "question": question_text,
        "deadline": deadline,
        "full_prompt": prompt_text
    }


def load_all_prompts(prompts_dir: str = None) -> List[Dict[str, str]]:
    """
    Load all period prompts (1-10)

    Args:
        prompts_dir: Directory containing prompt files

    Returns:
        List of dictionaries, one per period
    """
    prompts = []

    for period in range(1, 11):
        try:
            prompt_text = load_period_prompt(period, prompts_dir)
            question_info = extract_forecast_question(prompt_text)
            question_info['period'] = period
            prompts.append(question_info)
        except FileNotFoundError:
            print(f"[WARNING] Period {period} prompt not found, skipping")
            continue

    return prompts


def get_scenario_context(prompt_text: str) -> str:
    """
    Extract just the scenario context (initial briefing)

    Useful for providing background without the full prompt.

    Args:
        prompt_text: Full prompt text

    Returns:
        Scenario context section
    """

    # Try to extract scenario context section
    context_match = re.search(
        r'SCENARIO CONTEXT.*?\n(.*?)\n━',
        prompt_text,
        re.DOTALL
    )

    if context_match:
        return context_match.group(1).strip()

    # Fallback: return first few hundred characters
    return prompt_text[:500] + "..."


def get_period_developments(prompt_text: str) -> str:
    """
    Extract current period developments (events + actions)

    Args:
        prompt_text: Full prompt text

    Returns:
        Current period developments section
    """

    # Extract events
    events_match = re.search(
        r'<external_events>(.*?)</external_events>',
        prompt_text,
        re.DOTALL
    )
    events = events_match.group(1).strip() if events_match else ""

    # Extract actions
    actions_match = re.search(
        r'<observable_actions>(.*?)</observable_actions>',
        prompt_text,
        re.DOTALL
    )
    actions = actions_match.group(1).strip() if actions_match else ""

    if events or actions:
        developments = ""
        if events:
            developments += "MAJOR EVENTS:\n" + events + "\n\n"
        if actions:
            developments += "REPORTED ACTIONS:\n" + actions
        return developments.strip()

    return "No major developments reported."


def format_prompt_for_llm(period: int, include_sections: List[str] = None) -> str:
    """
    Format a prompt for LLM consumption

    Args:
        period: Period number
        include_sections: List of sections to include. Options:
            - "full" (default): entire prompt
            - "question_only": just the forecast question
            - "context": scenario context + question
            - "developments": current period + question

    Returns:
        Formatted prompt string
    """

    prompt_text = load_period_prompt(period)

    if include_sections is None or "full" in include_sections:
        return prompt_text

    # Build custom prompt
    formatted = ""

    if "context" in include_sections:
        formatted += get_scenario_context(prompt_text) + "\n\n"

    if "developments" in include_sections:
        formatted += get_period_developments(prompt_text) + "\n\n"

    # Always include the question
    question_info = extract_forecast_question(prompt_text)
    formatted += f"FORECAST QUESTION:\n{question_info['question']}\n"
    formatted += f"Deadline: {question_info['deadline']}"

    return formatted.strip()


if __name__ == "__main__":
    """Test the prompt loader"""

    print("=" * 80)
    print("PROMPT LOADER TEST")
    print("=" * 80)
    print()

    # Test loading a single period
    print("Loading Period 1 prompt...")
    try:
        prompt = load_period_prompt(1)
        print(f"[OK] Loaded {len(prompt)} characters")
        print()

        # Extract question
        question_info = extract_forecast_question(prompt)
        print("Extracted question info:")
        print(f"  Question: {question_info['question'][:100]}...")
        print(f"  Deadline: {question_info['deadline']}")
        print()

    except FileNotFoundError as e:
        print(f"[FAIL] {e}")
        print()

    # Test loading all prompts
    print("Loading all period prompts...")
    prompts = load_all_prompts()
    print(f"[OK] Loaded {len(prompts)} prompts")
    print()

    # Show summary
    print("=" * 80)
    print("PROMPT SUMMARY")
    print("=" * 80)
    for p in prompts:
        print(f"Period {p['period']:2d} - {p['deadline']:8s} - {p['question'][:60]}...")
    print()

    # Test different formatting
    print("=" * 80)
    print("FORMATTING TEST - Period 5")
    print("=" * 80)
    print()

    print("--- FULL PROMPT ---")
    full = format_prompt_for_llm(5, ["full"])
    print(f"Length: {len(full)} characters")
    print(full[:500] + "...\n")

    print("--- QUESTION ONLY ---")
    question = format_prompt_for_llm(5, ["question_only"])
    print(question)
    print()

    print("=" * 80)
    print("[OK] Prompt loader tests complete!")
    print("=" * 80)
